name: FM Monitor Scheduled Run

on:
  schedule:
    - cron: '0 0-12 * * *'  # UTC 0~12 = 北京时间 8:00~20:00
  workflow_dispatch:

jobs:
  run-fm-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run FM Monitor script
        env:
          FROM_ADDR: ${{ secrets.FROM_ADDR }}
          TO_ADDR: ${{ secrets.TO_ADDR }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python fm_monitor_re.py
